# Locale
export LANG="fr_FR.UTF-8"

# Autorisation sur l'affichage
#xhost + &> /dev/null

export XDG_DATA_HOME=$HOME/.local/share
export XDG_DATA_DIRS=$XDG_DATA_HOME:$XDG_DATA_DIRS

# Function/completion zsh
export FPATH=~/.local/share/zsh/site-functions/:/usr/local/share/zsh/site-functions/:$FPATH

# Viewer/Editeur par defaut (pour Crontab, CVS,...)
export VISUAL="vim"
export EDITOR="vim"
export PAGER="less"
export LESSOPEN="|/usr/bin/lesspipe %s"
export PAGER=less
# Man page en couleur
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline


#case 
# Permissions rw-r--r-- pour les fichiers crées
# et rwxr-xr-x pour les répertoires crées
umask 022

# Proxy HTTP / FTP sans mot de passe
PROXY_HOST=localhost
PROXY_PORT=8888
NO_PROXY='127.0.0.1,localhost'
export http_proxy="http://$PROXY_HOST:$PROXY_PORT"
export https_proxy=$http_proxy
export ftp_proxy=$http_proxy
export no_proxy=$NO_PROXY
export HTTP_PROXY=$http_proxy
export HTTPS_PROXY=$https_proxy
export NO_PROXY=$NO_PROXY
# Proxy HTTP / FTP avec mot de passe
#export http_proxy="http://login:password@proxy.exemple.org:8080"
#export ftp_proxy="ftp://login:password@proxy.exemple.org:8080"
export SOAP_USE_PROXY=on
export soap_use_proxy=on

# Ne pas passer par le proxy pour les domaines locaux
#export no_proxy="exemple.org"

#export LESSOPEN="|/usr/bin/lesspipe %s"
#export LESSCHARSET=utf-8

# Java
export JAVA_HOME="/opt/product/jdk"
JAVA_PROXY_ARG="-Dhttp.proxyHost=$PROXY_HOST -Dhttp.proxyPort=$PROXY_PORT -Dhttp.nonProxyHosts=$NO_PROXY -Dhttps.proxyHost=$PROXY_HOST -Dhttps.proxyPort=$PROXY_PORT -Dhttps.nonProxyHosts=$NO_PROXY"
#export CLASSPATH=/usr/share/java/:/usr/local/share/java/
export JAVA_OPTS=$JAVA_PROXY_ARG
export GLASSFISH_HOME=/opt/product/glassfish3/glassfish
export AS_ADMIN_PORT=4848
export AS_ADMIN_HOST=localhost
export PGHOST=localhost
export PGUSER=
export GREP_COLOR=auto
export ANT_HOME=/opt/product/ant
export ANT_ARGS="-logger org.apache.tools.ant.listener.AnsiColorLogger"
export ANT_OPTS="-Xmx1024m -XX:PermSize=128m -XX:MaxPermSize=128m $JAVA_PROXY_ARG"
export MAVEN_OPTS="-Xmx256m -XX:MaxPermSize=256m -Dmaven.artifact.threads=20 $JAVA_PROXY_ARG"
export MAVEN_HOME=/opt/product/maven 
export M2_HOME=$MAVEN_HOME
export GRADLE_HOME=/opt/product/gradle/
#export ORACLE_HOME=/usr/lib/oracle/11.2/client
#export TNS_ADMIN=/etc/oracle
export PHP_HOME=/opt/product/php-5.4/
export PYTHON27_HOME=/opt/product/python/python2.7
export PYTHON3_HOME=/opt/product/python/python3
export LOGSTASH_HOME=/opt/product/logstash/
export WIRESHARK_HOME=/opt/product/wireshark/
export TEXLIVE_HOME=/home/cynoffic/texlive/2014/

export MANPATH=$TEXLIVE_HOME/bin/x86_64-linux/:/opt/product/user/share/man/:$JAVA_HOME/man:$WIRESHARK_HOME/share/man:$PYTHON3_HOME/share/man:$PYTHON27_HOME/share/man:$PHP_HOME/php/man:$MANPATH

export PATH=~/bin:~/usr/bin:$PYTHON3_HOME/bin:$PYTHON27_HOME/bin:/opt/product/python/python2.7/bin:/opt/product/user/bin:~/.local/bin:~/usr/bin:~/scripts:$PATH:$JAVA_HOME/bin:$ANT_HOME/bin:$GRADLE_HOME/bin:$ORACLE_HOME/bin:~/bin:$GLASSFISH_HOME/bin:$PHP_HOME/bin:$LOGSTASH_HOME/bin:$WIRESHARK_HOME/bin:/usr/hs/bin/:$HOME/.cabal/bin


export MANPATH=$PHP_HOME/php/man:$JAVA_HOME/man:$MANPATH


